
version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/bank_app
      - SECRET_KEY=supersecretkey
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db

  studentportfolio:
    build: ./studentportfolio
    ports:
      - "3000:80"
    hostname: studentportfolio
    container_name: studentportfolio
    restart: unless-stopped

volumes:
  mongo_data:
